export const EventNames = {
  MerchantCreated: "merchant.created",
  MerchantDeleted: "merchant.deleted",
  MerchantSuspended: "merchant.suspended",
  ConversationStarted: "conversation.started",
  ConversationEnded: "conversation.ended",
  MessageSent: "message.sent",
  RecommendationMade: "recommendation.made",
  PurchaseCompleted: "purchase.completed",
  AIResponseGenerated: "ai.response.generated",
  HumanHandoffRequested: "human.handoff.requested",
  KnowledgeIndexed: "knowledge.indexed",
  KnowledgeFailed: "knowledge.failed",
  ImportStarted: "import.started",
  ImportCompleted: "import.completed",
  PaymentSucceeded: "payment.succeeded",
  PaymentFailed: "payment.failed",
  AdminLogin: "admin.login",
  WidgetInstalled: "widget.installed",
  FeatureToggled: "feature.toggled",
  QueueHealth: "queue.health",
  InfrastructureMetric: "infrastructure.metric",
  VisitorConnected: "visitor.connected",
  VisitorDisconnected: "visitor.disconnected",
} as const;
